copyright = "© Neal Wang"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/Los_Angeles"
timeout = "120s"
title = "Gallery"

[params]
  defaultTheme = "dark"
  description = "Creative Portfolio - Photography & Digital Arts"
  title = "Neal Wang's Gallery"
  [params.author]
    email = "nealwang.sh@protonmail.com"
    name = "Neal Wang"
  [params.socialIcons]
	# facebook = "https://www.facebook.com/"
    instagram = "https://www.instagram.com/nealwang.art"
    github = "https://github.com/neowsl"
    youtube = "https://www.youtube.com/@neowsl"
    email = "mailto:nealwang.sh+art@protonmail.com"
    website = "https://neowsl.github.io"
    # mastodon = "https://example.com"
    # pixelfed = "https://example.com"
    # mixcloud = "https://mixcloud.com"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

# [menu]
#   [[menu.footer]]
#     name = "GitHub"
#     url = "https://github.com/nicokaiser/hugo-theme-gallery/"
#     weight = 3

[services]
  [services.rss]
    limit = 100
